Repository devops-fall-20-inventory/inventories, pull requests merged in 2020-10, with the labels that each got.

#24 .gitignore (python)
  .gitignore
Labels: Environment, technical debt

#25 Create setup.cfg
  setup.cfg
Labels: Environment, technical debt

#26 DB Schema 1
  IMG_1182.JPG
  devops-inventory-data-model-1.png
  devops-inventory-data-model-2.png
Labels: Design, core requirement

#49 [test-model] automated testing through test case data file
  tests/data_to_test.csv
  tests/inventory_factory.py
  tests/test_model.py
  tests/test_service.py
Labels: Implementation

#61 [pylint] increased score to 9.81
  service/__init__.py
  service/model.py
  service/service.py
  tests/test_model.py
  tests/test_service.py
Labels: core requirement

#73 Created the .travis.yml file
  .travis.yml
Labels: Environment

#82 [readme-doc] beautified the README
  README.md
Labels: Documentation
