Repository devops-fall-20-inventory/inventories, pull requests merged in 2020-11, with the labels that each got.

#89 [ibm] deploy to IBM
  .pylintrc
  Procfile
  README.md
  Vagrantfile
  config.py
  manifest.yml
  runtime.txt
  service/__init__.py
  service/service.py
  tests/test_model.py
  tests/test_service.py
Labels: core requirement

#94 [Ibm cd] README codecov badge
  .travis.yml
  README.md
  service/model.py
  service/service.py
  setup.cfg
  tests/test_model.py
  tests/test_service.py
Labels: bug

#98 Pre-BDD modifications
  .pylintrc
  README.md
  features/environment.py
  features/inventory.feature
  features/steps/inventory_steps.py
  service/error_handlers.py
  service/model.py
  service/service.py
  service/static/css/blue_bootstrap.min.css
  service/static/css/darkly_bootstrap.min.css
  service/static/css/flatly_bootstrap.min.css
  service/static/css/slate_bootstrap.min.css
  service/static/images/newapp-icon.png
  service/static/index.html
  service/static/js/jquery-3.1.1.min.js
  service/static/js/rest_api.js
  setup.cfg
  tests/test_error_handlers.py
  tests/test_model.py
  tests/test_service.py
Labels: bug, core requirement

#117 BDD update
  features/inventory.feature
Labels: core requirement

#130 [miscellaneous] backlog and bug fixes
  .travis.yml
  features/environment.py
  features/inventory.feature
  features/steps/inventory_steps.py
  manifest.yml
  service/model.py
  service/routes.py
  service/static/js/rest_api.js
  tests/test_model.py
  tests/test_routes.py
Labels: bug, technical debt
